baseURL = "/"
title = "GhostESP Documentation"
theme = "ghostesp"
defaultContentLanguage = "en"
canonifyURLs = false
enableRobotsTXT = true

[params]
  subtitle = ""

[params.versioning]
  default = "latest"

[[params.versioning.options]]
  id = "latest"
  name = "Latest"

[[params.versioning.options]]
  id = "v2.1"
  name = "v2.1"

[[params.versioning.options]]
  id = "v1.9.9"
  name = "v1.9.9"

[[params.versioning.options]]
  id = "v1.9.8"
  name = "v1.9.8"

[[params.versioning.options]]
  id = "v1.9.3"
  name = "v1.9.3"

[[params.versioning.options]]
  id = "v1.9"
  name = "v1.9"

[[params.versioning.options]]
  id = "v1.8.1"
  name = "v1.8.1"


[[params.versioning.options]]
  id = "v1.8"
  name = "v1.8"


[outputFormats.searchindex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true

[outputFormats.aitext]
  mediaType = "text/plain"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputFormats.llmstxt]
  mediaType = "text/plain"
  baseName = "llms"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "JSON", "searchindex", "llmstxt"]
  section = ["HTML", "JSON", "searchindex", "aitext"]
  page = ["HTML", "aitext"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github-dark"


